### ISSUE TITLE
Move membership serializer code to organizations app

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/presspass-frontend#18]

**Comment by jacqui** [comment]
I've moved the user-membership serializer and viewset code to the organizations app, along with making the corrections that Mitch mentioned in [Squarelet PR #32](https://github.com/MuckRock/squarelet/pull/32).

One of his requested changes could be a little problematic for us and I want to 🎏flag it with you:

I had added the UUID for an invitation to the data returned for it (`PressPassNestedInvitationSerializer`) by the API. Mitch said this shouldn't have been added, so I removed it... but I'm not sure how we'll get the UUID for the invitation without this change. Note that we need the UUID in order to accept/reject/update invitations. And that's, as with everything I say, as far as I know at least 🤓✌️😉
