### ISSUE TITLE
Figure out what plans, if any, a default user should be signed up for

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/presspass-frontend#49]
For user registration to work, I had to change line 143 of squarelet/users/viewsets.py to `        data["plan"] = None`. That's because the standard Free plan is for group organization as well, and we don't assign a new user to a group organization.

Should we:

- Create a PressPass Free Plan for individuals, and default to that on sign up?
- Have no plan, and make some entitlements available to anyone.

Effectively the same solution, just about what's right for the database.

**Comment by jacqui** [comment]
Hrm... I can confirm that changing line 143 as you mentioned makes registration work for me as well. 

After some digging, it seems like the code is a little problematic though, as it seems to assume that a plan being "for groups" means the current user is part of a group organization.

The thing about creating a PressPass Free Plan for individuals separate from the free plan for groups is that we'll have to change the Plan model from having those two boolean (for_individuals/for_groups) flags to a group vs individual flag, right? I worry about the amount of changes that would require in the API as well.

Then I also wonder how we'd handle the no-plan solution in the API.

**Comment by jacqui** [comment]
As a follow-up to what I said about finding the code problematic, my initial take was that I'd want to change the `register_user` method in the `UserManager`:

* where it's checking if the plan is `for_groups`, also check that `organization_name` is present
* and that the organization given as `organization_name` is a group, not an individual org
* instead of assuming all of the above and trying to create a subscription

I might be missing something here though...?

**Comment by TylerFisher** [comment]
I don't think we'd have to change the API or model at all, we just create a plan that is set as True for individuals and False for groups. And given how we plan to resolve #53, I think that's probably the easiest solution. We won't have a way to scope entitlements as for everyone, we'll access them exclusively through plans.

**Comment by jacqui** [comment]
Oh! Okay, cool. I understand 👍
